### ISSUE TITLE
Managing quotes for attachment filename + optional blob checking

### ISSUE THREAD

**Issue by myselfhimself** [zenstruck/mailer-test#19]
Hello,

if some controller sends an email with an attachment, that attachment may have spaces or non-ASCII characters (for any reasons..)...
The MimeType header for that attachment may be something like:
1) `application/octet-stream; name=filename.pdf` (in place)
OR
2) `application/octet-stream; name="filename whatever.pdf"` (not tolerated by Zenstruck's mailer test)
OR possibly a variant with single quotes

So far the check relies on the filename to deduce the above header construction:

https://github.com/zenstruck/mailer-test/blob/1.x/src/TestEmail.php#L254

Could the code please tolerate body headers with or without simple or double quotes for mime-type + filename?

**Comment by myselfhimself** [comment]
Sometimes the attached file binary data is flaky / variable...
Which makes that we may do want to compare filename, mimeType... but not blob data.
At best, `TestEmail->assertHasFile()` should provide optional parameter values...

**Comment by kbond** [comment]
Interesting, can you show me a code example where single quotes and double quotes would be used? I'd like to create a failing test.

**Comment by myselfhimself** [comment]
Per https://blog.nodemailer.com/2017/01/27/the-mess-that-is-attachment-filenames/
```
Subject: This is a test message↵
MIME-Version: 1.0↵
Content-Type: multipart/mixed; boundary=abc↵
↵
--abc↵
Content-Type: text/plain↵
↵
Test content↵
↵
--abc↵
Content-Type: application/octet-stream;↵
    name="test.txt"↵
Content-Transfer-Encoding: base64↵
↵
Q2F0↵
--abc--↵
```

and
```
Content-Disposition: attachment;↵
    filename*=utf-8''%F0%9F%98%81%F0%9F%98%82.txt
```

[Here filename= has quotes... But it seems there are not always quotes on the web...](https://unix.stackexchange.com/questions/401667/parsing-filename-from-raw-email)

I am using `Symfony\Bridge\Twig\Mime\TemplatedEmail`

```
        $email = (new TemplatedEmail())
            ->from($from)
            ->to($to)
            ->subject($subject)
            ->attach($invoicePdf, $this->fileHelper->getInvoicePdfFileName($invoice))
            ->htmlTemplate('email/invoice/send.html.twig')
            ->context($context);

            $this->mailer->send($email);

```

Excerpt from my unit test:
```
        // bugged assertHasFile, see https://github.com/zenstruck/mailer-test/issues/19
        //        $sentEmail->assertHasFile(
        //            sprintf('"%s"', ),
        //            'application/octet-stream',
        //            $this->pdfService->createInvoicePdf($randomUnsentContractlessInvoice)
        //        );
        $expectedFilename = $this->fileHelper->getInvoicePdfFileName($randomUnsentContractlessInvoice);
        $expectedContentType = 'application/octet-stream';

        $this->assertCount(1, $sentEmail->getAttachments());
        $attachment = $sentEmail->getAttachments()[0];
        $this->assertEquals($expectedFilename, $sentEmail->getAttachments()[0]->getPreparedHeaders()->get('content-disposition')->getParameter('filename'));
        $this->assertEquals($expectedContentType.'; name="'.$expectedFilename.'"', $attachment->getPreparedHeaders()->get('content-type')->getBodyAsString());
        // Not comparing unstable PDF output
        //$this->assertEquals($this->pdfService->createInvoicePdf($randomUnsentContractlessInvoice), $attachment->getBody());
```

Thank you!

**Comment by kbond** [comment]
@myselfhimself, can you test #20 and see if this fixes your problem?

I'd still like to add a test for this. Above, can you give an example of what `$this->fileHelper->getInvoicePdfFileName($invoice)` returns that causes quotes?

**Comment by myselfhimself** [comment]
Hello, `$this->fileHelper->getInvoicePdfFileName($invoice)` returns a PHP String without quotes itself:
- either `invoice-17.pdf`
- or `invoice-A Fixture generated Invoice Id 17.pdf`

I will test #20 tomorrow. Thank you very much for being so reactive!

**Comment by myselfhimself** [comment]
What would be nice is to have `assertHasFile()`'s parameters 2 (mime typing) and 3 (binary blob) to be optional.
Namely in my case, the binary blob is not generated idempotently by my PDF generator (wkhtmltopdf from a twig template), so I have no way to test with assertHasFile() because of its compulsory parameter 3.

**Comment by kbond** [comment]
> or invoice-A Fixture generated Invoice Id 17.pdf

Ah, quotes are added when the filename has a space. Thanks, #20 now includes a test to prove it works.

> What would be nice is to have assertHasFile()'s parameters 2 (mime typing) and 3 (binary blob) to be optional.

Agreed! I'm going to add this to #20.

**Comment by kbond** [comment]
I've merged #20 so test the latest 1.x branch. If it works for you I'll tag a release.

**Comment by myselfhimself** [comment]
Hello, just git cloned branch.

```
        $sentEmail->assertHasFile(
            $this->fileHelper->getInvoicePdfFileName($randomUnsentContractlessInvoice), // with value like: "aah-invoice-2022-01-56 (from quote).pdf" (without quotes in string)
            'application/octet-stream',
//            $this->pdfService->createInvoicePdf($randomUnsentContractlessInvoice)
        );
```
is passing.

```
        $sentEmail->assertHasFile(
            $this->fileHelper->getInvoicePdfFileName($randomUnsentContractlessInvoice),
//            'application/octet-stream',
//            $this->pdfService->createInvoicePdf($randomUnsentContractlessInvoice)
        );
```
is passing.

Testing weasyprint instead of knpsnappy (wkhtmltopdf) to ensure pdf idempotency maybe..

**Comment by myselfhimself** [comment]
weasyprint isn't idempotent as well... will not test more

**Comment by kbond** [comment]
Thanks, I've created a release.

**Comment by myselfhimself** [comment]
Release tested and fruitful thank you.
