### ISSUE TITLE
Sent emails should be persisted between kernel reboots

### ISSUE THREAD

**Issue by kbond** [zenstruck/mailer-test#5]
The following doesn't currently work:

```php
// ...some code that sends 2 emails...
// reboot kernel
$this->mailer()->assertSentEmailCount(2);
```

It needs to be modified to the following to work:

```php
// ...some code that sends 2 emails...
$this->mailer()->assertSentEmailCount(2);
// reboot kernel
```

I believe the only way to achieve this is to add a lightweight bundle that registers a listener for `MessageEvent` and stores them statically (and resets them after the test). This would be similar to how zenstruck/messenger-test works.

This will also remove the requirement for the profiler to be enabled on some versions of Symfony: https://github.com/zenstruck/mailer-test/blob/4b13884702706246d2f57174649cf6bb438f168d/tests/InteractsWithMailerTest.php#L173-L206

**Comment by OskarStark** [comment]
cc @silasjoisten
